using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using NUnit.Framework;
using TestProject;

namespace TestProject.Tests
{
    [TestFixture]
    public class AnotherTestClassTest
    {
        [Test]
        public void Test1()
        {
            Assert.Fail("autogenerated");
        }

        [Test]
        public void Test2()
        {
            Assert.Fail("autogenerated");
        }

        [Test]
        public void Test3()
        {
            Assert.Fail("autogenerated");
        }
    }
}