using System;
using NUnit.Framework;
using TestProject;

namespace TestProject.Tests
{
    [TestFixture]
    public class TestClassTest
    {
        [Test]
        public void Test1()
        {
            Assert.Fail("autogenerated");
        }

        [Test]
        public void Test2()
        {
            Assert.Fail("autogenerated");
        }

        [Test]
        public void Test3()
        {
            Assert.Fail("autogenerated");
        }
    }
}